FROM mhart/alpine-node:latest

RUN addgroup -g 1000 -S node && \
  adduser -u 1000 -S node -G node

# Create and define the node_modules's cache directory.
WORKDIR /usr/cache

# Install the application's dependencies into the node_modules's cache directory.
COPY package.json ./
COPY package-lock.json ./
RUN npm install

# Create and define the application's working directory.
RUN mkdir /usr/app
WORKDIR /usr/app

COPY entrypoint.sh ./
RUN chmod +x /usr/app/entrypoint.sh

RUN apk add --no-cache bash
