version: '3.5'

services:
  u11_express_server:
    build:
      context: ./server
      dockerfile: ./deploy/Dockerfile-dev
    command: npm run dev
    volumes:
      - ./server:/usr/app/
      - ./server/node_modules:/usr/app/node_modules
  u11_react_client:
    command: npm run start
    volumes:
      - ./client:/usr/app/
      - ./client/node_modules:/usr/app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
  adminmongo:
    environment:
      - HOST=0.0.0.0